### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by WayneStratton** [AmmoCan/contact-form-7-google-places-api#1]
Hey dude, great plugin idea! One question, I can't seem to kick this thing off. I entered my API key into 'contact-form-7-google-places-api.php' on line 40 and then used contact form 7 to input a shortcode with a placeholder. Am I missing something?

**Comment by AmmoCan** [comment]
Hey Wayne, thanx for the support! Sorry to hear about your issue, but thank you for bringing it to my attention. My bad, it seems I did forget an important detail. When using the 'Places Text Field' tag type — In the 'Form-tag Generator: Places Text Field' you must enter "autocomplete" without quotes as the value for the 'Id attribute' field. Please let me know if I can be of any further assistance.

**Comment by WayneStratton** [comment]
I will check this out and let you know. Thanks man!

**Comment by WayneStratton** [comment]
Hey bud, weird but that didn't change anything for me. Just to double check:

Added the address tag to my form with autocomplete as the value for "ID Attribute", as well as added placeholder text

Using Google Places API key in the plugin file 

Anything else you can think of off hand I missed? I've used the Places API via a function before with no problem so this one has me stumped. Maybe I have API setup wrong? When I set it up for this use case I just generated one that's labeled "Server" from your Places API hyperlink in the readme. Thanks again!

**Comment by AmmoCan** [comment]
Hey Wayne, thanx for following up with me! I don't think you are using the right API key. I went to this url: https://developers.google.com/maps/documentation/javascript/get-api-key and followed the instructions to get the API key.

Sorry if the instructions weren't clear on that, as I tried making them so. Let me know if this solves your issue.

**Comment by AmmoCan** [comment]
Also, once you have your key be sure to replace the entire: 'ENTER YOUR API KEY HERE' string with the key. Not sure if you are entering inside the single quotes, but I could see how that could happen.

**Comment by WayneStratton** [comment]
Ugh, too bad man. I can't seem to get this to work. Just to make sure I did the API right I deleted the project and started from your link again. Setup a browser key as per the instructions, copied it it at 'ENTER YOUR API KEY HERE' (Overwriting the quotes as well). My form already has the tag along with autocomplete in the ID attribute field. From everything I can tell it should be working fine. :( When I go to key in an address I just get autocompletes from chrome for addresses I have entered before. What a bummer!

**Comment by WayneStratton** [comment]
Also just for clarity sake - I have the Google Places Web Service API along with the Google Maps JS API enabled in my project.

**Comment by AmmoCan** [comment]
Well, I assure you it works, so there has to be something going on on your end. Here is an example of it working out in the wild: http://shieldcorpssecurity.com

By any chance, on the credentials page for your Google Maps JS API Browser Key did you add any referrers in the 'Accept requests from these HTTP referrers (web sites)' field? Google has it marked as optional, but then in the description states, "Be sure to add referrers before using this key in production". I found, that even when using the key in development you still need to add a referrer. I have an asterisk as my referrer.

I look forward to hearing back from you!

**Comment by WayneStratton** [comment]
Thanks again for all the help! Not sure what the deal is. I have referrers in there, a few actually. I am working off a sub domain and am using both the primary domain and subdomain in there. What the hell! All plugins/themes are off besides 2015, Contact Form 7, and the Contact Form 7 Places plugin. 

It boggles my mind that it's not working actually. When I view the console on your production version as well as the demo from the original plugin creators broken plugin, both flag a Google Maps API related error but it works fine on those examples. When I view my form, I get no error and it doesn't work at all.. HA! Who knows! I really do appreciate all the help trying to get it working though.

As a last ditch effort, here is the screen shots of how I have the key setup (I removed my prior referrers and added your asterisk in) https://cloudup.com/ct-H9txmFFr

**Comment by AmmoCan** [comment]
No problem bud! I want to try and do everything I can to assist you in getting this to work for you.

Yeah, I know it works, so I am just as dumb founded as you to why it isn't working for you. The warning for the Google Maps API in the production use case is because it is in fact not using an API key as the warning states. The reason being is because I first created this plugin last year and at that time you didn't need an API Key. The reason it is still working is because Google grandfathered all applications using their APIs, so anything created before their mandated API Key requirement will still work without one. Yeah, the creators plugin, which motivated me to create this plugin is a hot mess...

From the looks of it, it seems you are doing everything correct. The only thing I can think of is maybe you are not pasting your contact form 7 short-code in the page you have designated as the front-page. Could that be it?
