### ISSUE TITLE
Does plugin work across multiple pages within a WordPresss site?

### ISSUE THREAD

**Issue by sheridangray** [AmmoCan/contact-form-7-google-places-api#3]

**Comment by AmmoCan** [comment]
@sheridangray The plugin is currently only set up to work with one designated page at a time. Please feel free to fork the plugin and modify it to suit your needs, as that was one of my reasons for making it public. The 'is_page()' function does take an array as an argument, so you should have no issues in modifying the 'gpa_page' option field to be an array. However, if I was to do this, and I might at a later date, I would probably implement a multi-select dropdown of all the pages available.
